name: Test

on:
  pull_request:
    types: [closed]

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: testfile
        key: cache-${{ github.sha }}
        restore-keys: cache-
    - run: |
        echo $GITHUB_REF
        echo $GITHUB_REF > testfile
